CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" character varying(256),
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Paises" (
    "CodPais" integer GENERATED BY DEFAULT AS IDENTITY,
    "Pais" text NOT NULL,
    "Sigla" text NOT NULL,
    "DDI" text NOT NULL,
    "Moeda" text NOT NULL,
    CONSTRAINT "PK_Paises" PRIMARY KEY ("CodPais")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserPasskeys" (
    "CredentialId" bytea NOT NULL,
    "UserId" text NOT NULL,
    "Data" jsonb NOT NULL,
    CONSTRAINT "PK_AspNetUserPasskeys" PRIMARY KEY ("CredentialId"),
    CONSTRAINT "FK_AspNetUserPasskeys_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Estados" (
    "CodEstado" integer GENERATED BY DEFAULT AS IDENTITY,
    "Estado" text NOT NULL,
    "UF" text NOT NULL,
    "oPaisCodPais" integer NOT NULL,
    CONSTRAINT "PK_Estados" PRIMARY KEY ("CodEstado"),
    CONSTRAINT "FK_Estados_Paises_oPaisCodPais" FOREIGN KEY ("oPaisCodPais") REFERENCES "Paises" ("CodPais") ON DELETE CASCADE
);

CREATE TABLE "Cidades" (
    "CodCidade" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cidade" text NOT NULL,
    "oEstadoCodEstado" integer NOT NULL,
    CONSTRAINT "PK_Cidades" PRIMARY KEY ("CodCidade"),
    CONSTRAINT "FK_Cidades_Estados_oEstadoCodEstado" FOREIGN KEY ("oEstadoCodEstado") REFERENCES "Estados" ("CodEstado") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserPasskeys_UserId" ON "AspNetUserPasskeys" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Cidades_oEstadoCodEstado" ON "Cidades" ("oEstadoCodEstado");

CREATE INDEX "IX_Estados_oPaisCodPais" ON "Estados" ("oPaisCodPais");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260411174813_InicialSalao', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Estados" ADD "CodPais" integer NOT NULL DEFAULT 0;

ALTER TABLE "Cidades" ADD "CodEstado" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260411191917_PagesIniciais', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Cidades" DROP CONSTRAINT "FK_Cidades_Estados_oEstadoCodEstado";

ALTER TABLE "Estados" DROP CONSTRAINT "FK_Estados_Paises_oPaisCodPais";

DROP INDEX "IX_Estados_oPaisCodPais";

DROP INDEX "IX_Cidades_oEstadoCodEstado";

ALTER TABLE "Estados" DROP COLUMN "oPaisCodPais";

ALTER TABLE "Cidades" DROP COLUMN "oEstadoCodEstado";

CREATE INDEX "IX_Estados_CodPais" ON "Estados" ("CodPais");

CREATE INDEX "IX_Cidades_CodEstado" ON "Cidades" ("CodEstado");

ALTER TABLE "Cidades" ADD CONSTRAINT "FK_Cidades_Estados_CodEstado" FOREIGN KEY ("CodEstado") REFERENCES "Estados" ("CodEstado") ON DELETE CASCADE;

ALTER TABLE "Estados" ADD CONSTRAINT "FK_Estados_Paises_CodPais" FOREIGN KEY ("CodPais") REFERENCES "Paises" ("CodPais") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260411220822_AjusteChavesEstrangeiras', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Pessoas" DROP CONSTRAINT "FK_Pessoas_Cidades_oCidadeCodCidade";

DROP INDEX "IX_Pessoas_oCidadeCodCidade";

ALTER TABLE "Pessoas" DROP COLUMN "oCidadeCodCidade";

ALTER TABLE "Pessoas" ALTER COLUMN "UltimaVisita" TYPE timestamp without time zone;

ALTER TABLE "Pessoas" ALTER COLUMN "Telefone" DROP NOT NULL;

ALTER TABLE "Pessoas" ALTER COLUMN "Email" DROP NOT NULL;

ALTER TABLE "Pessoas" ALTER COLUMN "DataNascimento" TYPE timestamp without time zone;

ALTER TABLE "Pessoas" ALTER COLUMN "DataDemissao" TYPE timestamp without time zone;

ALTER TABLE "Pessoas" ALTER COLUMN "DataCadastro" TYPE timestamp without time zone;

ALTER TABLE "Pessoas" ALTER COLUMN "DataAdmissao" TYPE timestamp without time zone;

CREATE INDEX "IX_Pessoas_CodCidade" ON "Pessoas" ("CodCidade");

ALTER TABLE "Pessoas" ADD CONSTRAINT "FK_Pessoas_Cidades_CodCidade" FOREIGN KEY ("CodCidade") REFERENCES "Cidades" ("CodCidade") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260603000150_ConfiguracaoHerancaTPH', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TABLE "CondicoesPagamento" (
    "CodCondicao" integer GENERATED BY DEFAULT AS IDENTITY,
    "Descricao" character varying(50) NOT NULL,
    "NumeroParcelas" integer NOT NULL,
    "TaxaJuros" numeric(5,2) NOT NULL,
    "Desconto" numeric(5,2) NOT NULL,
    "PrazoDias" integer NOT NULL,
    "Ativo" boolean NOT NULL,
    CONSTRAINT "PK_CondicoesPagamento" PRIMARY KEY ("CodCondicao")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260608230415_AdicionaCondicaoPagamento', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "CondicoesPagamento" RENAME COLUMN "TaxaJuros" TO "Multa";

ALTER TABLE "CondicoesPagamento" RENAME COLUMN "PrazoDias" TO "PrimeiraParcela";

ALTER TABLE "CondicoesPagamento" ADD "EntreParcelas" integer NOT NULL DEFAULT 0;

ALTER TABLE "CondicoesPagamento" ADD "Juros" numeric(5,2) NOT NULL DEFAULT 0.0;

CREATE TABLE "CondicoesPagamentoParcelas" (
    "CodParcela" integer GENERATED BY DEFAULT AS IDENTITY,
    "CodCondicao" integer NOT NULL,
    "oCondicaoCodCondicao" integer NOT NULL,
    "Numero" integer NOT NULL,
    "Dias" integer NOT NULL,
    "Percentual" numeric(5,2) NOT NULL,
    CONSTRAINT "PK_CondicoesPagamentoParcelas" PRIMARY KEY ("CodParcela"),
    CONSTRAINT "FK_CondicoesPagamentoParcelas_CondicoesPagamento_oCondicaoCodC~" FOREIGN KEY ("oCondicaoCodCondicao") REFERENCES "CondicoesPagamento" ("CodCondicao") ON DELETE CASCADE
);

CREATE INDEX "IX_CondicoesPagamentoParcelas_oCondicaoCodCondicao" ON "CondicoesPagamentoParcelas" ("oCondicaoCodCondicao");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260608233149_AddCondicaoPagamento', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Pessoas" ALTER COLUMN "ComissaoPercentual" TYPE numeric(5,4);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260609004921_FixBug', '10.0.5');

COMMIT;

